#!/bin/sh                                                                                                                                                                                                 
LOG_FOLDER=/var/log/runit-man
mkdir -p $LOG_FOLDER
exec svlogd -tt $LOG_FOLDER
